/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type ChapterTranslationPhase =
  (typeof ChapterTranslationPhase)[keyof typeof ChapterTranslationPhase]

export const ChapterTranslationPhase = {
  preparing: 'preparing',
  translating: 'translating',
  post_processing: 'post_processing',
} as const
