/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { JobStatus } from './jobStatus'
import type { PipelineProgress } from './pipelineProgress'

export interface JobSummary {
  /** @nullable */
  error?: string | null
  id: string
  kind: string
  progress?: null | PipelineProgress
  status: JobStatus
}
