/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { ChapterTranslationPhase } from './chapterTranslationPhase'
import type { PipelineStatus } from './pipelineStatus'
import type { PipelineStep } from './pipelineStep'

export interface PipelineProgress {
  awaitingBatchReview?: boolean
  /**
   * Confirmed summaries from previous batches followed by the current
   * generated summary while awaiting review.
   * @nullable
   */
  batchSummaries?: string[] | null
  /** @nullable */
  batchSummary?: string | null
  chapterPhase?: null | ChapterTranslationPhase
  /**
   * @minimum 0
   * @nullable
   */
  chapterTotalPages?: number | null
  /**
   * One-based batch number for chapter translation jobs.
   * @minimum 0
   * @nullable
   */
  currentBatch?: number | null
  /** @minimum 0 */
  currentPage: number
  /** @minimum 0 */
  currentStepIndex: number
  jobId: string
  /** @minimum 0 */
  overallPercent: number
  /**
   * @minimum 0
   * @nullable
   */
  preparedPages?: number | null
  /**
   * @minimum 0
   * @nullable
   */
  renderedPages?: number | null
  status: PipelineStatus
  step?: null | PipelineStep
  /**
   * @minimum 0
   * @nullable
   */
  totalBatches?: number | null
  /** @minimum 0 */
  totalPages: number
  /** @minimum 0 */
  totalSteps: number
  /**
   * @minimum 0
   * @nullable
   */
  translatedPages?: number | null
}
