/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { LlmTarget } from './llmTarget'

export interface RetryChapterTranslationRequest {
  /** @minimum 0 */
  maxTokens: number
  target: LlmTarget
}
