/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { LlmTarget } from './llmTarget'

export interface StartChapterTranslationRequest {
  /**
   * @minimum 0
   * @nullable
   */
  batchSize?: number | null
  /** @nullable */
  brief?: string | null
  /** @nullable */
  defaultFont?: string | null
  /** @minimum 0 */
  maxTokens: number
  target: LlmTarget
  targetLanguage: string
}
